### ISSUE TITLE
Question about using

### ISSUE THREAD

**Issue by fredafredaf** [Tereshchenkolab/digitize-ecg-cli#1]
hi! thanks for the amazing work

I want to ask about the setup of this project: the "getting started" part in the readme stops at installing the requirement, and I am not so sure how to proceed from there. Does this repo also create a GUI app like the one in "page ECG", or does it create a library that I can use to digitize images without the GUI? (i'm trying to digitize many images for my assignment so it would be really great if I can pass them in all at once without using the GUI)

thanks in advance!

**Comment by tereshchenko9** [comment]
Hi ! Thank you for your interest! 
correct, the installation will create a GUI with a user-friendly interface. Code is also provided, look at both repositories (paper-ECG and ecg-digitize). feel free to use pieces of the code as you wish, for your purpose. From our experience, we find that it is useful to check the quality of digitizing on each ECG. Yes, it takes time, but it will reassure the quality of the digitized signal, which is important. Larisa
