### ISSUE TITLE
bin/digitize does nothing?

### ISSUE THREAD

**Issue by gerardsimons** [Tereshchenkolab/digitize-ecg-cli#2]
Hi there,

Thanks for making this, it seems perfect for me. I was wondering if there was a CLI option to call it and saw bin/digitize but it seems like all it does right now is echo the arguments. Is it work in progress? If not present I might make one myself, but just wondering... Thanks again !

**Comment by tereshchenko9** [comment]
please feel free to develop it further as fit your needs. thank you for your interest!
