### ISSUE TITLE
Text-label signal distortions

### ISSUE THREAD

**Issue by elijahrockers** [Tereshchenkolab/digitize-ecg-cli#3]
Great work, the signal is extracted beautifully, thank you.

Question: For the embedded lead labels on our ECG (e.g. "aVF" text), it looks like the letter "V" gets interpreted as part of the signal, and the signal can be distorted within the first 35 samples or so. There are also cases where the signal intercepts the text label, causing a similar distortion.

We may be able to collaborate with DSP groups on this noise, but I wanted to check if you know of any work already done on this. Don't want to reinvent the wheel. :)

**Comment by tereshchenko9** [comment]
Thank you for your good words! 
One solution is to "draw" the bounding box closer to the ECG waveform and keep the letters outside.
Feel free to develop that feature. No, I am not aware.
